// <auto-generated />
using System;
using Gozba_na_klik.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gozba_na_klik.Migrations
{
    [DbContext(typeof(GozbaNaKlikDbContext))]
    [Migration("20250928082233_AddRestaurantOwners")]
    partial class AddRestaurantOwners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.ClosedDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ClosedDates");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserImage")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "josipvaltner@gmail.com",
                            Password = "pass_jv",
                            Role = "Admin",
                            Username = "Josip_admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lukakovacevic@gmail.com",
                            Password = "pass_lk",
                            Role = "Admin",
                            Username = "Luka_admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "borislaketic@gmail.com",
                            Password = "pass_bl",
                            Role = "Admin",
                            Username = "Boris_admin"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kopasztamas@gmail.com",
                            Password = "pass_kt",
                            Role = "Admin",
                            Username = "Tamas_admin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "urosmilinovic@gmail.com",
                            Password = "pass_um",
                            Role = "Admin",
                            Username = "Uros_admin"
                        },
                        new
                        {
                            Id = 7,
                            Email = "milan.owner@example.com",
                            Password = "pass_mo",
                            Role = "RestaurantOwner",
                            Username = "Milan_owner"
                        },
                        new
                        {
                            Id = 8,
                            Email = "ana.owner@example.com",
                            Password = "pass_ao",
                            Role = "RestaurantOwner",
                            Username = "Ana_owner"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ivan.owner@example.com",
                            Password = "pass_io",
                            Role = "RestaurantOwner",
                            Username = "Ivan_owner"
                        });
                });

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.ClosedDate", b =>
                {
                    b.HasOne("Gozba_na_klik.Models.Restaurants.Restaurant", "Restaurant")
                        .WithMany("ClosedDates")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.Restaurant", b =>
                {
                    b.HasOne("Gozba_na_klik.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.WorkSchedule", b =>
                {
                    b.HasOne("Gozba_na_klik.Models.Restaurants.Restaurant", "Restaurant")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.User", b =>
                {
                    b.HasOne("Gozba_na_klik.Models.Restaurants.Restaurant", null)
                        .WithMany("Employees")
                        .HasForeignKey("RestaurantId");
                });

            modelBuilder.Entity("Gozba_na_klik.Models.Restaurants.Restaurant", b =>
                {
                    b.Navigation("ClosedDates");

                    b.Navigation("Employees");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
