// <auto-generated />
using Gozba_na_klik.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gozba_na_klik.Migrations
{
    [DbContext(typeof(GozbaNaKlikDbContext))]
    [Migration("20250922213601_FeatPredefinedAdminRoles")]
    partial class FeatPredefinedAdminRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gozba_na_klik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "josipvaltner@gmail.com",
                            Password = "pass_jv",
                            Role = "Admin",
                            Username = "Josip_admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lukakovacevic@gmail.com",
                            Password = "pass_lk",
                            Role = "Admin",
                            Username = "Luka_admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "borislaketic@gmail.com",
                            Password = "pass_bl",
                            Role = "Admin",
                            Username = "Boris_admin"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kopasztamas@gmail.com",
                            Password = "pass_kt",
                            Role = "Admin",
                            Username = "Tamas_admin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "urosmilinovic@gmail.com",
                            Password = "pass_um",
                            Role = "Admin",
                            Username = "Uros_admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
